### ISSUE TITLE
secrets "confluent-schema-registry" not found

### ISSUE THREAD

**Issue by benedictmulongo** [lsst-sqre/strimzi-registry-operator#105]
When I run:

```bash
kubectl -n kafka describe StrimziSchemaRegistry confluent-schema-registry
```
I get the error `secrets "confluent-schema-registry" not found`

```yaml
apiVersion: roundtable.lsst.codes/v1beta1
kind: StrimziSchemaRegistry
metadata:
  name: confluent-schema-registry
spec:
  strimziVersion: v1beta2
  listener: plainext
  serviceType: nodeport
  securityProtocol: plaintext
```
In the readme file https://github.com/lsst-sqre/strimzi-registry-operator there is no mentions of `confluent-schema-registry` and which values it should have. 

Moreover, how to get access to the schema-registry externally? Is it exposed at an certain port?

```bash
kubectl explain StrimziSchemaRegistry.spec
``` 
gives me no hints about port or host to access the schema registry.
