### ISSUE TITLE
Operator deployed always in the `default` namespace

### ISSUE THREAD

**Issue by darkwings** [lsst-sqre/strimzi-registry-operator#94]
I'm trying to deploy the operator in a dedicated namespace but, either via helm or Kustomize, the operator is installed in the `default` namespace.

### Helm
With helm, I tried

`helm install lsstsqre/strimzi-registry-operator --name ssr --set clusterNamespace=kafka,clusterName=my-cluster`

### Kustomize
With Kustomize I tried to follow the instructions of the README and apply the patch but the operator is always deployed in the `default` namespace, not in the one I want.

This was my process. I created a `patch` folder in which I added `kustomization.yaml`

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/lsst-sqre/strimzi-registry-operator.git//manifests?ref=0.5.0

patches:
  - strimzi-registry-operator-deployment.yaml
```

and `strimzi-registry-operator-deployment.yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-registry-operator
spec:
  template:
    spec:
      containers:
        - name: operator
          env:
            - name: SSR_CLUSTER_NAME
              value: my-cluster
            - name: SSR_NAMESPACE
              value: kafka
```

Then I apply the configuration with the command

```shell
kctl apply -k patch
```
